### ISSUE TITLE
Tend to use std::array instead of raw array in `Element` namespace

### ISSUE THREAD

**Issue by OpenSEMBA-user** [OpenSEMBA/core#10]
From OpenSEMBA created by [juliolopeztorres](https://github.com/juliolopeztorres): OpenSEMBA-user/OpenSEMBA#43  

Current use, example `Quadrilateral4.h`:

```cpp

    const Coordinate::Coordinate<T,3>* v_[4];

```

Preferred usage:

```cpp

    std::array<const Coordinate::Coordinate<T,3>*, 8> v_;

```

**Comment by lmdiazangulo** [comment]
Done
