### ISSUE TITLE
Strange `const` by-pass in `GiD`-`Exporter`

### ISSUE THREAD

**Issue by OpenSEMBA-user** [OpenSEMBA/core#3]
From OpenSEMBA created by [juliolopeztorres](https://github.com/juliolopeztorres): OpenSEMBA-user/OpenSEMBA#57  

There is a call to `applyScalingFactor` on `GiD.Exporter` scope that seems really strange. The `Data` being passed in is tagged as `const` but a call to `applyScalingFactor` is being made through the mesh via pointer. 

Compiler does not trigger any error. 

Is that correct?

[Code](https://github.com/OpenSEMBA-user/OpenSEMBA/blob/master/src/exporters/gid/Exporter.cpp#L56)

**Comment by lmdiazangulo** [comment]
Removed GiD exporting
